-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        dim_inactive = false,
        rounding = 0,
    },
    general = {
        gaps_in = 0,
        gaps_out = 0,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vrr = 1,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})

-- Keybinds
hl.unbind("ALT + W")
hl.bind("ALT + W", hl.dsp.exec_cmd("zen-browser"))
hl.bind("XF86Tools", hl.dsp.exec_cmd("hyprmod"))
