
################
### MONITORS ###
################

source = ~/.config/hypr/monitors.conf

###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty 
$fileManager = nautilus 
$menu = rofi -show drun

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal -e cbonsai -S
exec-once = nm-applet &
exec-once = waybar
exec-once = hyprpaper 
exec-once = ~/.local/bin/flare_0.1.0_amd64.AppImage


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_THEME, Skeuos-White-Dark
env = XCURSOR_THEME, Nordzy-hyprcursors
env = GTK_ICON_THEME, Papirus-Dark


###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

ecosystem {
  enforce_permissions = 1
}

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/aesthetics.conf

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1 
    accel_profile = flat

    sensitivity = .51 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
	disable_while_typing = true
	scroll_factor = 0.85
	clickfinger_behavior = true

    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gesture = 3, horizontal, workspace
gesture = 3, up, mod: SUPER, scale: 1.5, fullscreen
gesture = 3, down, scale: 1.5, float

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
device {
    name = logitech-usb-receiver
    sensitivity = 0.0
    accel_profile = flat
}

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/keybinds.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/workspaces.conf

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$


