-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        rounding = 0,
    },
    general = {
        gaps_in = 0,
        gaps_out = 0,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vrr = 1,
    },
})
