preload = /home/kohin/Picture/Wallpapers/lockscreen.jpg 
wallpaper = eDP-1, /home/kohin/Picture/Wallpapers/lockscreen.jpg 
wallpaper = desc:serial:H4CR200018E, /home/kohin/Picture/Wallpapers/lockscreen.jpg 
wallpaper = desc:serial:EBW8L01782SL0, /home/kohin/Picture/Wallpapers/lockscreen.jpg 

# Optional: don’t stretch weirdly, keep aspect
ipc = off

